version: '3.5'

services:
  db:
    container_name: pai_db
    image: postgres:13
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      TZ: America/Sao_Paulo
#      LANG: pt_BR.UTF-8
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready",
          "-U",
          $DB_USER "-d",
          $DB_NAME
        ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    volumes:
      - pai_database:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
  app:
    container_name: pai_app
    image: dmstr/php-yii2:7.4-fpm-8.0-nginx
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./:/app
    tmpfs:
      - /app/web/assets
      - /app/runtime
    ports:
      - "8090:80"
      - "8091:443"
    command: bash -c "chmod 777 /app/web/assets && chmod 777 /app/runtime && composer install && php ./yii migrate --interactive=0 && forego start -r -f /root/Procfile"
    depends_on:
      db:
        condition: service_healthy
    environment:
      PHP_ENABLE_XDEBUG: 0

volumes:
  pai_database:
    external: true
