version: '3.5'

services:
  app:
    env_file:
      - .env.development
    environment:
      YII_ENV: dev
    ports:
      - "8080:8080"
    command: bash -c "php ./yii migrate --interactive=0 && yii serve 0.0.0.0"