version: '3.3'

services:
  db:
    container_name: pai_db
    image: postgres:13
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      TZ: America/Sao_Paulo
#      LANG: pt_BR.UTF-8
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${DB_USER} -d ${DB_NAME}"
        ]
      interval: 2s
      timeout: 3s
      retries: 40
    volumes:
      - pai_database:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    networks:
      - default
  app:
    container_name: pai_app
    image: dmstr/php-yii2:7.4-fpm-8.0-nginx
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./:/app
      - ./nginx:/etc/nginx/conf.d
    tmpfs:
      - /app/web/assets
      - /app/runtime
    # ports:
    #   - "8090:80"
    #   - "8091:443"
    command: bash -c "chmod 777 /app/web/assets && chmod 777 /app/runtime && composer install && php ./yii migrate --interactive=0 && export XDEBUG_CONFIG=\"remote_connect_back=0 remote_enable=1 remote_host=172.17.0.1\" && supervisord -c  /etc/supervisor/supervisord.conf"
    depends_on:
      db:
        condition: service_healthy
    networks:
#      - nginx-proxy
      - default
    environment:
      PHP_ENABLE_XDEBUG: 0
      VIRTUAL_HOST: pai.bcc.anapolis.ifg.edu.br
      VIRTUAL_PORT: 8090
      LETSENCRYPT_HOST: pai.bcc.anapolis.ifg.edu.br

volumes:
  pai_database:
    external: true

#networks:
#  nginx-proxy:
#    external: true