version: '3.5'

services:
  app:
    env_file:
      - .env
    environment:
      YII_ENV: dev
    ports:
      - "8080:8080"
    command: bash -c "cd /usr/local/etc/php/conf.d/ && echo 'memory_limit = -1' >> /usr/local/etc/php/conf.d/docker-php-ram-limit.ini && cd /app && yii serve 0.0.0.0"