INSERT INTO public.disciplina_matriz (id, nome, sigla) VALUES (1, 'ALGEBRA LINEAR', 'ALLINEAR');
INSERT INTO public.disciplina_matriz (id, nome, sigla) VALUES (2, 'ANALISE E PROJETO DE SOFTWARE', 'APS');
INSERT INTO public.disciplina_matriz (id, nome, sigla) VALUES (3, 'ARQUITETURA E ORGANIZACAO DE COMPUTADORES I', 'AOC I');
INSERT INTO public.disciplina_matriz (id, nome, sigla) VALUES (4, 'ARQUITETURA E ORGANIZACAO DE COMPUTADORES II', 'AOC II');
INSERT INTO public.disciplina_matriz (id, nome, sigla) VALUES (5, 'BANCO DE DADOS I', 'BD I');
INSERT INTO public.disciplina_matriz (id, nome, sigla) VALUES (6, 'BANCO DE DADOS II', 'BD II');
INSERT INTO public.disciplina_matriz (id, nome, sigla) VALUES (7, 'CALCULO I', 'CAL I');
INSERT INTO public.disciplina_matriz (id, nome, sigla) VALUES (8, 'CALCULO II', 'CAL II');
INSERT INTO public.disciplina_matriz (id, nome, sigla) VALUES (9, 'COMPUTACAO GRAFICA', 'CG');
INSERT INTO public.disciplina_matriz (id, nome, sigla) VALUES (10, 'CONSTRUCAO DE ALGORITMOS', 'CO');
INSERT INTO public.disciplina_matriz (id, nome, sigla) VALUES (11, 'EDUCACAO DAS RELACOES ETNICO-RACIAIS E AFRODESCENDENCIA', 'RERA');
INSERT INTO public.disciplina_matriz (id, nome, sigla) VALUES (12, 'ENGENHARIA DE SOFTWARE', 'ENSOF');
INSERT INTO public.disciplina_matriz (id, nome, sigla) VALUES (13, 'ESTRUTURA DE DADOS I', 'ED I');
INSERT INTO public.disciplina_matriz (id, nome, sigla) VALUES (14, 'ESTRUTURA DE DADOS II', 'ED II');
INSERT INTO public.disciplina_matriz (id, nome, sigla) VALUES (15, 'ETICA, COMPUTADORES E SOCIEDADE', 'ECS');
INSERT INTO public.disciplina_matriz (id, nome, sigla) VALUES (16, 'FISICA APLICADA A CIENCIA DA COMPUTACAO', 'FISCC');
INSERT INTO public.disciplina_matriz (id, nome, sigla) VALUES (17, 'FUNDAMENTOS MATEMATICOS', 'FUMA');
INSERT INTO public.disciplina_matriz (id, nome, sigla) VALUES (18, 'GERENCIA DE PROJETOS - TOPICOS ESPECIAIS EM COMPUTACAO I', 'GP');
INSERT INTO public.disciplina_matriz (id, nome, sigla) VALUES (19, 'GRAMATICAS E COMPILADORES', 'GRC');
INSERT INTO public.disciplina_matriz (id, nome, sigla) VALUES (20, 'INTELIGENCIA ARTIFICIAL', 'IA');
INSERT INTO public.disciplina_matriz (id, nome, sigla) VALUES (21, 'INTERACAO HOMEM-MAQUINA', 'IHM');
INSERT INTO public.disciplina_matriz (id, nome, sigla) VALUES (22, 'INTRODUCAO A CIENCIA DA COMPUTACAO', 'INCC');
INSERT INTO public.disciplina_matriz (id, nome, sigla) VALUES (23, 'INTRODUCAO AOS SISTEMAS DIGITAIS', 'SIDI');
INSERT INTO public.disciplina_matriz (id, nome, sigla) VALUES (24, 'IOT - TOPICOS ESPECIAIS EM COMPUTACAO II', 'IOT');
INSERT INTO public.disciplina_matriz (id, nome, sigla) VALUES (25, 'LABORATORIO DE PROGRAMACAO', 'PROG');
INSERT INTO public.disciplina_matriz (id, nome, sigla) VALUES (26, 'LOGICA E MATEMATICA DISCRETA', 'LMD');
INSERT INTO public.disciplina_matriz (id, nome, sigla) VALUES (27, 'MATEMATICA COMPUTACIONAL', 'MC');
INSERT INTO public.disciplina_matriz (id, nome, sigla) VALUES (28, 'METODOLOGIA DE PESQUISA CIENTIFICA', 'MPC');
INSERT INTO public.disciplina_matriz (id, nome, sigla) VALUES (29, 'MINERACAO DE DADOS', 'MIDA');
INSERT INTO public.disciplina_matriz (id, nome, sigla) VALUES (30, 'OTIMIZACAO DE SISTEMAS', 'OSIS');
INSERT INTO public.disciplina_matriz (id, nome, sigla) VALUES (31, 'PARADIGMAS DE PROGRAMACAO', 'PP');
INSERT INTO public.disciplina_matriz (id, nome, sigla) VALUES (32, 'PROBABILDADE E ESTATISTICA', 'PRES');
INSERT INTO public.disciplina_matriz (id, nome, sigla) VALUES (33, 'PROCESSAMENTO DIGITAL DE IMAGENS', 'PDI');
INSERT INTO public.disciplina_matriz (id, nome, sigla) VALUES (34, 'PROGRAMACAO DE DISPOSITIVOS MOVEIS', 'PRMOV');
INSERT INTO public.disciplina_matriz (id, nome, sigla) VALUES (35, 'PROGRAMACAO ORIENTADA A OBJETOS', 'POO');
INSERT INTO public.disciplina_matriz (id, nome, sigla) VALUES (36, 'PROGRAMACAO WEB', 'PW');
INSERT INTO public.disciplina_matriz (id, nome, sigla) VALUES (37, 'PROJETO AVANCADO DE ALGORITMOS', 'PAA');
INSERT INTO public.disciplina_matriz (id, nome, sigla) VALUES (38, 'REDES DE COMPUTADORES', 'RC');
INSERT INTO public.disciplina_matriz (id, nome, sigla) VALUES (39, 'SISTEMAS DISTRIBUIDOS', 'SDIS');
INSERT INTO public.disciplina_matriz (id, nome, sigla) VALUES (40, 'SISTEMAS OPERACIONAIS', 'SIOP');
INSERT INTO public.disciplina_matriz (id, nome, sigla) VALUES (41, 'TEORIA DA COMPUTACAO', 'TEOC');
INSERT INTO public.disciplina_matriz (id, nome, sigla) VALUES (42, 'TEORIA DOS GRAFOS', 'TEGRA');
INSERT INTO public.disciplina_matriz (id, nome, sigla) VALUES (43, 'TRABALHO DE CONCLUSAO DE CURSO I', 'TCC I');
INSERT INTO public.disciplina_matriz (id, nome, sigla) VALUES (44, 'TRABALHO DE CONCLUSAO DE CURSO II', 'TCC II');
INSERT INTO public.disciplina_matriz (id, nome, sigla) VALUES (45, 'TOPICOS ESPECIAIS EM COMPUTACAO I', 'TEC I');
INSERT INTO public.disciplina_matriz (id, nome, sigla) VALUES (46, 'TOPICOS ESPECIAIS EM COMPUTACAO II', 'TEC II');