INSERT INTO public.disciplina (id, nome, ano, semestre, id_professor, id_disciplina_matriz) VALUES (1, 'ANALISE E PROJETO DE SOFTWARE', 2018, 2, 11, 2);
INSERT INTO public.disciplina (id, nome, ano, semestre, id_professor, id_disciplina_matriz) VALUES (2, 'ARQUITETURA E ORGANIZACAO DE COMPUTADORES II', 2018, 2, 6, 4);
INSERT INTO public.disciplina (id, nome, ano, semestre, id_professor, id_disciplina_matriz) VALUES (3, 'BANCO DE DADOS I', 2018, 2, 11, 5);
INSERT INTO public.disciplina (id, nome, ano, semestre, id_professor, id_disciplina_matriz) VALUES (4, 'CALCULO I', 2018, 2, 5, 7);
INSERT INTO public.disciplina (id, nome, ano, semestre, id_professor, id_disciplina_matriz) VALUES (5, 'CALCULO II', 2018, 2, 7, 8);
INSERT INTO public.disciplina (id, nome, ano, semestre, id_professor, id_disciplina_matriz) VALUES (6, 'COMPUTACAO GRAFICA', 2018, 2, 16, 9);
INSERT INTO public.disciplina (id, nome, ano, semestre, id_professor, id_disciplina_matriz) VALUES (7, 'ESTRUTURA DE DADOS I', 2018, 2, 16, 13);
INSERT INTO public.disciplina (id, nome, ano, semestre, id_professor, id_disciplina_matriz) VALUES (8, 'INTELIGENCIA ARTIFICIAL', 2018, 2, 4, 20);
INSERT INTO public.disciplina (id, nome, ano, semestre, id_professor, id_disciplina_matriz) VALUES (9, 'INTRODUCAO A CIENCIA DA COMPUTACAO', 2018, 2, 6, 22);
INSERT INTO public.disciplina (id, nome, ano, semestre, id_professor, id_disciplina_matriz) VALUES (10, 'INTRODUCAO AOS SISTEMAS DIGITAIS', 2018, 2, 6, 23);
INSERT INTO public.disciplina (id, nome, ano, semestre, id_professor, id_disciplina_matriz) VALUES (11, 'MATEMATICA COMPUTACIONAL', 2018, 2, 6, 27);
INSERT INTO public.disciplina (id, nome, ano, semestre, id_professor, id_disciplina_matriz) VALUES (12, 'METODOLOGIA DE PESQUISA CIENTIFICA', 2018, 2, 11, 28);
INSERT INTO public.disciplina (id, nome, ano, semestre, id_professor, id_disciplina_matriz) VALUES (13, 'PROGRAMACAO ORIENTADA A OBJETOS', 2018, 2, 9, 35);
INSERT INTO public.disciplina (id, nome, ano, semestre, id_professor, id_disciplina_matriz) VALUES (14, 'PROGRAMACAO WEB', 2018, 2, 9, 36);
INSERT INTO public.disciplina (id, nome, ano, semestre, id_professor, id_disciplina_matriz) VALUES (15, 'PROJETO AVANCADO DE ALGORITMOS', 2018, 2, 16, 37);
INSERT INTO public.disciplina (id, nome, ano, semestre, id_professor, id_disciplina_matriz) VALUES (16, 'TEORIA DA COMPUTACAO', 2018, 2, 9, 41);
INSERT INTO public.disciplina (id, nome, ano, semestre, id_professor, id_disciplina_matriz) VALUES (17, 'EDUCACAO DAS RELACOES ETNICO-RACIAIS E AFRODESCENDENCIA', 2018, 2, 17, 11);
INSERT INTO public.disciplina (id, nome, ano, semestre, id_professor, id_disciplina_matriz) VALUES (18, 'ALGEBRA LINEAR', 2019, 1, 3, 1);
INSERT INTO public.disciplina (id, nome, ano, semestre, id_professor, id_disciplina_matriz) VALUES (19, 'ARQUITETURA E ORGANIZACAO DE COMPUTADORES I', 2019, 1, 6, 3);
INSERT INTO public.disciplina (id, nome, ano, semestre, id_professor, id_disciplina_matriz) VALUES (20, 'CALCULO II', 2019, 1, 7, 8);
INSERT INTO public.disciplina (id, nome, ano, semestre, id_professor, id_disciplina_matriz) VALUES (21, 'CONSTRUCAO DE ALGORITMOS', 2019, 1, 2, 10);
INSERT INTO public.disciplina (id, nome, ano, semestre, id_professor, id_disciplina_matriz) VALUES (22, 'ENGENHARIA DE SOFTWARE', 2019, 1, 2, 12);
INSERT INTO public.disciplina (id, nome, ano, semestre, id_professor, id_disciplina_matriz) VALUES (23, 'ESTRUTURA DE DADOS II', 2019, 1, 16, 14);
INSERT INTO public.disciplina (id, nome, ano, semestre, id_professor, id_disciplina_matriz) VALUES (24, 'ETICA, COMPUTADORES E SOCIEDADE', 2019, 1, 10, 15);
INSERT INTO public.disciplina (id, nome, ano, semestre, id_professor, id_disciplina_matriz) VALUES (25, 'FISICA APLICADA A CIENCIA DA COMPUTACAO', 2019, 1, 8, 16);
INSERT INTO public.disciplina (id, nome, ano, semestre, id_professor, id_disciplina_matriz) VALUES (26, 'FUNDAMENTOS MATEMATICOS', 2019, 1, 5, 17);
INSERT INTO public.disciplina (id, nome, ano, semestre, id_professor, id_disciplina_matriz) VALUES (27, 'GRAMATICAS E COMPILADORES', 2019, 1, 9, 19);
INSERT INTO public.disciplina (id, nome, ano, semestre, id_professor, id_disciplina_matriz) VALUES (28, 'INTRODUCAO A CIENCIA DA COMPUTACAO', 2019, 1, 6, 22);
INSERT INTO public.disciplina (id, nome, ano, semestre, id_professor, id_disciplina_matriz) VALUES (29, 'MINERACAO DE DADOS', 2019, 1, 4, 29);
INSERT INTO public.disciplina (id, nome, ano, semestre, id_professor, id_disciplina_matriz) VALUES (30, 'PROGRAMACAO DE DISPOSITIVOS MOVEIS', 2019, 1, 2, 34);
INSERT INTO public.disciplina (id, nome, ano, semestre, id_professor, id_disciplina_matriz) VALUES (31, 'PROGRAMACAO WEB', 2019, 1, 9, 36);
INSERT INTO public.disciplina (id, nome, ano, semestre, id_professor, id_disciplina_matriz) VALUES (32, 'SISTEMAS OPERACIONAIS', 2019, 1, 6, 40);
INSERT INTO public.disciplina (id, nome, ano, semestre, id_professor, id_disciplina_matriz) VALUES (33, 'TEORIA DOS GRAFOS', 2019, 1, 7, 42);
INSERT INTO public.disciplina (id, nome, ano, semestre, id_professor, id_disciplina_matriz) VALUES (34, 'TRABALHO DE CONCLUSAO DE CURSO I', 2019, 1, 7, 43);
INSERT INTO public.disciplina (id, nome, ano, semestre, id_professor, id_disciplina_matriz) VALUES (35, 'ANALISE E PROJETO DE SOFTWARE', 2019, 2, 11, 2);
INSERT INTO public.disciplina (id, nome, ano, semestre, id_professor, id_disciplina_matriz) VALUES (36, 'BANCO DE DADOS I', 2019, 2, 9, 5);
INSERT INTO public.disciplina (id, nome, ano, semestre, id_professor, id_disciplina_matriz) VALUES (37, 'CALCULO I', 2019, 2, 5, 7);
INSERT INTO public.disciplina (id, nome, ano, semestre, id_professor, id_disciplina_matriz) VALUES (38, 'ESTRUTURA DE DADOS I', 2019, 2, 9, 13);
INSERT INTO public.disciplina (id, nome, ano, semestre, id_professor, id_disciplina_matriz) VALUES (39, 'INTRODUCAO AOS SISTEMAS DIGITAIS', 2019, 2, 6, 23);
INSERT INTO public.disciplina (id, nome, ano, semestre, id_professor, id_disciplina_matriz) VALUES (40, 'PROGRAMACAO ORIENTADA A OBJETOS', 2019, 2, 2, 35);
INSERT INTO public.disciplina (id, nome, ano, semestre, id_professor, id_disciplina_matriz) VALUES (41, 'ARQUITETURA E ORGANIZACAO DE COMPUTADORES II', 2019, 2, 6, 4);
INSERT INTO public.disciplina (id, nome, ano, semestre, id_professor, id_disciplina_matriz) VALUES (42, 'ETICA, COMPUTADORES E SOCIEDADE', 2019, 2, 10, 15);
INSERT INTO public.disciplina (id, nome, ano, semestre, id_professor, id_disciplina_matriz) VALUES (43, 'LOGICA E MATEMATICA DISCRETA', 2019, 2, 13, 26);
INSERT INTO public.disciplina (id, nome, ano, semestre, id_professor, id_disciplina_matriz) VALUES (44, 'MATEMATICA COMPUTACIONAL', 2019, 2, 6, 27);
INSERT INTO public.disciplina (id, nome, ano, semestre, id_professor, id_disciplina_matriz) VALUES (45, 'PARADIGMAS DE PROGRAMACAO', 2019, 2, 11, 31);
INSERT INTO public.disciplina (id, nome, ano, semestre, id_professor, id_disciplina_matriz) VALUES (46, 'REDES DE COMPUTADORES', 2019, 2, 2, 38);
INSERT INTO public.disciplina (id, nome, ano, semestre, id_professor, id_disciplina_matriz) VALUES (47, 'COMPUTACAO GRAFICA', 2019, 2, 9, 9);
INSERT INTO public.disciplina (id, nome, ano, semestre, id_professor, id_disciplina_matriz) VALUES (48, 'INTELIGENCIA ARTIFICIAL', 2019, 2, 4, 20);
INSERT INTO public.disciplina (id, nome, ano, semestre, id_professor, id_disciplina_matriz) VALUES (49, 'OTIMIZACAO DE SISTEMAS', 2019, 2, 7, 30);
INSERT INTO public.disciplina (id, nome, ano, semestre, id_professor, id_disciplina_matriz) VALUES (50, 'TEORIA DA COMPUTACAO', 2019, 2, 9, 41);
INSERT INTO public.disciplina (id, nome, ano, semestre, id_professor, id_disciplina_matriz) VALUES (51, 'SISTEMAS DISTRIBUIDOS', 2019, 2, 6, 39);
INSERT INTO public.disciplina (id, nome, ano, semestre, id_professor, id_disciplina_matriz) VALUES (52, 'TOPICOS ESPECIAIS EM COMPUTACAO I', 2019, 2, 11, 45);
INSERT INTO public.disciplina (id, nome, ano, semestre, id_professor, id_disciplina_matriz) VALUES (53, 'TOPICOS ESPECIAIS EM COMPUTACAO II', 2019, 2, 2, 46);
INSERT INTO public.disciplina (id, nome, ano, semestre, id_professor, id_disciplina_matriz) VALUES (54, 'TRABALHO DE CONCLUSAO DE CURSO II', 2019, 2, 7, 44);
INSERT INTO public.disciplina (id, nome, ano, semestre, id_professor, id_disciplina_matriz) VALUES (55, 'PROBABILDADE E ESTATISTICA', 2019, 1, 13, 32);
INSERT INTO public.disciplina (id, nome, ano, semestre, id_professor, id_disciplina_matriz) VALUES (56, 'INTERACAO HOMEM-MAQUINA', 2019, 1, 11, 21);
INSERT INTO public.disciplina (id, nome, ano, semestre, id_professor, id_disciplina_matriz) VALUES (57, 'PROCESSAMENTO DIGITAL DE IMAGENS', 2019, 1, 16, 33);
INSERT INTO public.disciplina (id, nome, ano, semestre, id_professor, id_disciplina_matriz) VALUES (58, 'LABORATORIO DE PROGRAMACAO', 2019, 1, 11, 25);