INSERT INTO public.disciplina (id, nome, ano, semestre, id_professor, id_disciplina_matriz) VALUES (84, 'ANÁLISE E PROJETO DE SOFTWARE ', 2020, 2, 9, 2);
INSERT INTO public.disciplina (id, nome, ano, semestre, id_professor, id_disciplina_matriz) VALUES (85, 'ARQUITETURA E ORGANIZAÇÃO DE COMPUTADORES II ', 2020, 2, 6, 4);
INSERT INTO public.disciplina (id, nome, ano, semestre, id_professor, id_disciplina_matriz) VALUES (86, 'BANCO DE DADOS I ', 2020, 2, 4, 5);
INSERT INTO public.disciplina (id, nome, ano, semestre, id_professor, id_disciplina_matriz) VALUES (87, 'CÁLCULO I ', 2020, 2, 20, 7);
INSERT INTO public.disciplina (id, nome, ano, semestre, id_professor, id_disciplina_matriz) VALUES (88, 'COMPUTAÇÃO GRÁFICA ', 2020, 2, 9, 9);
INSERT INTO public.disciplina (id, nome, ano, semestre, id_professor, id_disciplina_matriz) VALUES (89, 'ESTRUTURAS DE DADOS I ', 2020, 2, 21, 13);
INSERT INTO public.disciplina (id, nome, ano, semestre, id_professor, id_disciplina_matriz) VALUES (90, 'ÉTICA, COMPUTADORES E SOCIEDADE ', 2020, 2, 10, 15);
INSERT INTO public.disciplina (id, nome, ano, semestre, id_professor, id_disciplina_matriz) VALUES (91, 'INTELIGÊNCIA ARTIFICIAL ', 2020, 2, 4, 20);
INSERT INTO public.disciplina (id, nome, ano, semestre, id_professor, id_disciplina_matriz) VALUES (92, 'INTRODUÇÃO AOS SISTEMAS DIGITAIS', 2020, 2, 19, 23);
INSERT INTO public.disciplina (id, nome, ano, semestre, id_professor, id_disciplina_matriz) VALUES (93, 'LABORATÓRIO DE PROGRAMAÇÃO', 2020, 2, 2, 25);
INSERT INTO public.disciplina (id, nome, ano, semestre, id_professor, id_disciplina_matriz) VALUES (94, 'LÓGICA E MATEMÁTICA DISCRETA ', 2020, 2, 13, 26);
INSERT INTO public.disciplina (id, nome, ano, semestre, id_professor, id_disciplina_matriz) VALUES (95, 'MATEMÁTICA COMPUTACIONAL ', 2020, 2, 6, 27);
INSERT INTO public.disciplina (id, nome, ano, semestre, id_professor, id_disciplina_matriz) VALUES (96, 'OTIMIZAÇÃO DE SISTEMAS ', 2020, 2, 7, 30);
INSERT INTO public.disciplina (id, nome, ano, semestre, id_professor, id_disciplina_matriz) VALUES (97, 'PARADIGMAS DE PROGRAMAÇÃO', 2020, 2, 19, 31);
INSERT INTO public.disciplina (id, nome, ano, semestre, id_professor, id_disciplina_matriz) VALUES (98, 'PROGRAMAÇÃO ORIENTADA A OBJETOS', 2020, 2, 2, 35);
INSERT INTO public.disciplina (id, nome, ano, semestre, id_professor, id_disciplina_matriz) VALUES (99, 'PROJETO AVANÇADO DE ALGORITMOS ', 2020, 2, 19, 37);
INSERT INTO public.disciplina (id, nome, ano, semestre, id_professor, id_disciplina_matriz) VALUES (100, 'REDES DE COMPUTADORES ', 2020, 2, 2, 38);
INSERT INTO public.disciplina (id, nome, ano, semestre, id_professor, id_disciplina_matriz) VALUES (101, 'SISTEMAS DISTRIBUÍDOS ', 2020, 2, 6, 39);
INSERT INTO public.disciplina (id, nome, ano, semestre, id_professor, id_disciplina_matriz) VALUES (102, 'TEORIA DA COMPUTAÇÃO ', 2020, 2, 9, 41);
INSERT INTO public.disciplina (id, nome, ano, semestre, id_professor, id_disciplina_matriz) VALUES (103, 'TÓPICOS ESPECIAIS EM COMPUTAÇÃO I', 2020, 2, 2, 45);
INSERT INTO public.disciplina (id, nome, ano, semestre, id_professor, id_disciplina_matriz) VALUES (104, 'TÓPICOS ESPECIAIS EM COMPUTAÇÃO II', 2020, 2, 21, 46);
